# permissions for end users to view edgenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: edgenode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-controller-manager
    app.kubernetes.io/part-of: cloud-controller-manager
    app.kubernetes.io/managed-by: kustomize
  name: edgenode-viewer-role
rules:
- apiGroups:
  - managemenet.coxedge.io
  resources:
  - edgenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managemenet.coxedge.io
  resources:
  - edgenodes/status
  verbs:
  - get
